# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1001)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_img1 = QtWidgets.QLabel(self.centralwidget)
        self.label_img1.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.label_img1.setScaledContents(False)
        self.label_img1.setObjectName("label_img1")
        self.label_dirName = QtWidgets.QLabel(self.centralwidget)
        self.label_dirName.setGeometry(QtCore.QRect(10, 920, 521, 20))
        self.label_dirName.setObjectName("label_dirName")
        self.label_img2 = QtWidgets.QLabel(self.centralwidget)
        self.label_img2.setGeometry(QtCore.QRect(800, 0, 800, 800))
        self.label_img2.setScaledContents(False)
        self.label_img2.setObjectName("label_img2")
        self.pushButton_hard1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hard1.setGeometry(QtCore.QRect(1682, 570, 75, 23))
        self.pushButton_hard1.setObjectName("pushButton_hard1")
        self.pushButton_hard2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hard2.setGeometry(QtCore.QRect(1760, 570, 75, 23))
        self.pushButton_hard2.setObjectName("pushButton_hard2")
        self.pushButton_sha1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sha1.setGeometry(QtCore.QRect(1682, 455, 71, 23))
        self.pushButton_sha1.setObjectName("pushButton_sha1")
        self.pushButton_sha2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sha2.setGeometry(QtCore.QRect(1763, 455, 75, 23))
        self.pushButton_sha2.setObjectName("pushButton_sha2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1682, 430, 121, 17))
        self.label_5.setObjectName("label_5")
        self.label_shadow = QtWidgets.QLabel(self.centralwidget)
        self.label_shadow.setGeometry(QtCore.QRect(1810, 430, 30, 16))
        self.label_shadow.setObjectName("label_shadow")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1682, 486, 90, 17))
        self.label_6.setObjectName("label_6")
        self.label_lightSource = QtWidgets.QLabel(self.centralwidget)
        self.label_lightSource.setGeometry(QtCore.QRect(1810, 490, 30, 16))
        self.label_lightSource.setObjectName("label_lightSource")
        self.pushButton_pro1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pro1.setGeometry(QtCore.QRect(1680, 360, 91, 23))
        self.pushButton_pro1.setObjectName("pushButton_pro1")
        self.pushButton_pro2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pro2.setGeometry(QtCore.QRect(1780, 360, 91, 23))
        self.pushButton_pro2.setObjectName("pushButton_pro2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1682, 542, 108, 17))
        self.label_7.setObjectName("label_7")
        self.label_hardSample = QtWidgets.QLabel(self.centralwidget)
        self.label_hardSample.setGeometry(QtCore.QRect(1810, 542, 30, 16))
        self.label_hardSample.setObjectName("label_hardSample")
        self.pushButton_lig1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lig1.setGeometry(QtCore.QRect(1682, 511, 75, 23))
        self.pushButton_lig1.setObjectName("pushButton_lig1")
        self.pushButton_lig2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lig2.setGeometry(QtCore.QRect(1840, 510, 75, 23))
        self.pushButton_lig2.setObjectName("pushButton_lig2")
        self.label_problems = QtWidgets.QLabel(self.centralwidget)
        self.label_problems.setGeometry(QtCore.QRect(1790, 330, 91, 21))
        self.label_problems.setObjectName("label_problems")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1680, 220, 191, 131))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1679, 741, 151, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_one = QtWidgets.QLabel(self.centralwidget)
        self.label_one.setGeometry(QtCore.QRect(1680, 810, 48, 16))
        self.label_one.setObjectName("label_one")
        self.label_all = QtWidgets.QLabel(self.centralwidget)
        self.label_all.setGeometry(QtCore.QRect(1734, 810, 46, 17))
        self.label_all.setObjectName("label_all")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1680, 849, 71, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1763, 848, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1761, 771, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1680, 771, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_lig2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lig2_2.setGeometry(QtCore.QRect(1760, 510, 75, 23))
        self.pushButton_lig2_2.setObjectName("pushButton_lig2_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 820, 1531, 101))
        self.label.setObjectName("label")
        self.pushButton_hard2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hard2_2.setGeometry(QtCore.QRect(1840, 570, 75, 23))
        self.pushButton_hard2_2.setObjectName("pushButton_hard2_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1690, 90, 221, 111))
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(1680, 890, 71, 41))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(1770, 890, 71, 41))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 810, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(990, 810, 54, 12))
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1700, 660, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.select_root_dir)
        self.pushButton_2.clicked.connect(MainWindow.last_dir)
        self.pushButton_3.clicked.connect(MainWindow.next_dir)
        self.pushButton_4.clicked.connect(MainWindow.jump_to_dir)
        self.pushButton_pro1.clicked.connect(MainWindow.hege)
        self.pushButton_pro2.clicked.connect(MainWindow.buhege)
        self.pushButton_sha1.clicked.connect(MainWindow.qingxi)
        self.pushButton_sha2.clicked.connect(MainWindow.buqingxi)
        self.pushButton_lig1.clicked.connect(MainWindow.shenyinying)
        self.pushButton_lig2_2.clicked.connect(MainWindow.zhongdengyinying)
        self.pushButton_lig2.clicked.connect(MainWindow.qianyinying)
        self.pushButton_hard1.clicked.connect(MainWindow.da)
        self.pushButton_hard2.clicked.connect(MainWindow.zhong)
        self.pushButton_hard2_2.clicked.connect(MainWindow.xiao)
        self.toolButton.clicked.connect(MainWindow.show_detail)
        self.toolButton_2.clicked.connect(MainWindow.show_detail_right)
        self.pushButton_5.clicked.connect(MainWindow.changeShadow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "双图标记工具V1.0"))
        self.label_img1.setText(_translate("MainWindow", "图片"))
        self.label_dirName.setText(_translate("MainWindow", "图片名"))
        self.label_img2.setText(_translate("MainWindow", "图片"))
        self.pushButton_hard1.setText(_translate("MainWindow", "大"))
        self.pushButton_hard2.setText(_translate("MainWindow", "中"))
        self.pushButton_sha1.setText(_translate("MainWindow", "清晰"))
        self.pushButton_sha2.setText(_translate("MainWindow", "不清晰"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#aa0000;\">*阴影是否清晰：</span></p></body></html>"))
        self.label_shadow.setText(_translate("MainWindow", "状态2"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#aa0000;\">*阴影深浅:</span></p></body></html>"))
        self.label_lightSource.setText(_translate("MainWindow", "状态3"))
        self.pushButton_pro1.setText(_translate("MainWindow", "合格"))
        self.pushButton_pro2.setText(_translate("MainWindow", "不合格"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#aa0000;\">*阴影大小:</span></p></body></html>"))
        self.label_hardSample.setText(_translate("MainWindow", "状态4"))
        self.pushButton_lig1.setText(_translate("MainWindow", "深阴影"))
        self.pushButton_lig2.setText(_translate("MainWindow", "浅阴影"))
        self.label_problems.setText(_translate("MainWindow", "状态1"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><tr><td width=\"193\"><p><span style=\" font-size:14pt; font-weight:600;\">内容是否一致</span></p></td></tr><tr><td><p><span style=\" font-size:14pt; font-weight:600;\">内容是否模糊</span></p></td></tr><tr><td><p><span style=\" font-size:14pt; font-weight:600;\">颜色亮度是否一致</span></p></td></tr><tr><td><p><span style=\" font-size:14pt; font-weight:600;\">阴影部分是否有反光</span></p></td></tr></table><p>有一个就是不合格：</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "选择文件夹"))
        self.label_one.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">当前数量</p></body></html>"))
        self.label_all.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">/ 总数</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "跳转到"))
        self.pushButton_3.setText(_translate("MainWindow", "下一张（D）"))
        self.pushButton_2.setText(_translate("MainWindow", "上一张（A）"))
        self.pushButton_lig2_2.setText(_translate("MainWindow", "中等阴影"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>清晰的定义为：手动描边，能把阴影区域的轮廓画出来。非清晰的阴影，轮廓模糊，从深到浅有明显亮度渐变的；清晰的阴影，例如手机、手掌的影子，轮廓规则。如果出现阴影内部有深浅渐变，但轮廓清晰规则的，或者有一侧明显轮廓一侧模糊的，以轮廓为准，视为清晰。</p><p>判断阴影的深浅情况，主要观察同一材质表面，阴影内和非阴影区域的对比度情况，对于难以归类到深或浅的，归于中等程度。</p><p>定性记录阴影占画面面积，只考虑两张图差异部分的阴影，对于物体本身出现的背影、明暗起伏，不予考虑。分为：大（超过2/3）、中、小（不足1/3）</p></body></html>"))
        self.pushButton_hard2_2.setText(_translate("MainWindow", "小"))
        self.label_2.setText(_translate("MainWindow", "不合格的不需要标注下面3项"))
        self.toolButton.setText(_translate("MainWindow", "左图细节"))
        self.toolButton_2.setText(_translate("MainWindow", "右图细节"))
        self.label_3.setText(_translate("MainWindow", "正常图片"))
        self.label_8.setText(_translate("MainWindow", "阴影图片"))
        self.pushButton_5.setText(_translate("MainWindow", "交换阴影图片"))
