# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labelImgUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1931, 1020)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 106, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 142, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 106, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 142, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 106, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 106, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 142, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 106, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 106, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 213, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(140, 10, 1471, 981))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-20, 0, 1489, 939))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(1489, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.toolButton_preImg = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_preImg.setGeometry(QtCore.QRect(0, 220, 141, 71))
        self.toolButton_preImg.setObjectName("toolButton_preImg")
        self.toolButton_imgdir = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_imgdir.setGeometry(QtCore.QRect(0, 10, 141, 71))
        self.toolButton_imgdir.setObjectName("toolButton_imgdir")
        self.toolButton_nextImg = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_nextImg.setGeometry(QtCore.QRect(0, 150, 141, 71))
        self.toolButton_nextImg.setObjectName("toolButton_nextImg")
        self.toolButton_zoom_in = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_zoom_in.setGeometry(QtCore.QRect(0, 290, 141, 71))
        self.toolButton_zoom_in.setObjectName("toolButton_zoom_in")
        self.toolButton_zoom_out = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_zoom_out.setGeometry(QtCore.QRect(0, 360, 141, 71))
        self.toolButton_zoom_out.setObjectName("toolButton_zoom_out")
        self.toolButton_save_path = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_save_path.setGeometry(QtCore.QRect(0, 80, 141, 71))
        self.toolButton_save_path.setObjectName("toolButton_save_path")
        self.toolButton_push_one = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_one.setGeometry(QtCore.QRect(1750, 10, 141, 71))
        self.toolButton_push_one.setObjectName("toolButton_push_one")
        self.toolButton_one = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_one.setGeometry(QtCore.QRect(1610, 10, 141, 71))
        self.toolButton_one.setObjectName("toolButton_one")
        self.toolButton_two = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_two.setGeometry(QtCore.QRect(1610, 80, 141, 71))
        self.toolButton_two.setObjectName("toolButton_two")
        self.toolButton_push_two = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_two.setGeometry(QtCore.QRect(1750, 80, 141, 71))
        self.toolButton_push_two.setObjectName("toolButton_push_two")
        self.toolButton_push_three = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_three.setGeometry(QtCore.QRect(1750, 150, 141, 71))
        self.toolButton_push_three.setObjectName("toolButton_push_three")
        self.toolButton_three = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_three.setGeometry(QtCore.QRect(1610, 150, 141, 71))
        self.toolButton_three.setObjectName("toolButton_three")
        self.toolButton_push_four = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_four.setGeometry(QtCore.QRect(1750, 220, 141, 71))
        self.toolButton_push_four.setObjectName("toolButton_push_four")
        self.toolButton_four = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_four.setGeometry(QtCore.QRect(1610, 220, 141, 71))
        self.toolButton_four.setObjectName("toolButton_four")
        self.toolButton_push_five = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_five.setGeometry(QtCore.QRect(1750, 290, 141, 71))
        self.toolButton_push_five.setObjectName("toolButton_push_five")
        self.toolButton_five = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_five.setGeometry(QtCore.QRect(1610, 290, 141, 71))
        self.toolButton_five.setObjectName("toolButton_five")
        self.toolButton_push_six = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_six.setGeometry(QtCore.QRect(1750, 360, 141, 71))
        self.toolButton_push_six.setObjectName("toolButton_push_six")
        self.toolButton_six = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_six.setGeometry(QtCore.QRect(1610, 360, 141, 71))
        self.toolButton_six.setObjectName("toolButton_six")
        self.toolButton_push_seven = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_seven.setGeometry(QtCore.QRect(1750, 430, 141, 71))
        self.toolButton_push_seven.setObjectName("toolButton_push_seven")
        self.toolButton_seven = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_seven.setGeometry(QtCore.QRect(1610, 430, 141, 71))
        self.toolButton_seven.setObjectName("toolButton_seven")
        self.toolButton_eight = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_eight.setGeometry(QtCore.QRect(1610, 500, 141, 71))
        self.toolButton_eight.setObjectName("toolButton_eight")
        self.toolButton_push_eight = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_eight.setGeometry(QtCore.QRect(1750, 500, 141, 71))
        self.toolButton_push_eight.setObjectName("toolButton_push_eight")
        self.toolButton_nine = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_nine.setGeometry(QtCore.QRect(1610, 570, 141, 71))
        self.toolButton_nine.setObjectName("toolButton_nine")
        self.toolButton_push_nine = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_nine.setGeometry(QtCore.QRect(1750, 570, 141, 71))
        self.toolButton_push_nine.setObjectName("toolButton_push_nine")
        self.toolButton_ten = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_ten.setGeometry(QtCore.QRect(1610, 640, 141, 71))
        self.toolButton_ten.setObjectName("toolButton_ten")
        self.toolButton_push_ten = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_ten.setGeometry(QtCore.QRect(1750, 640, 141, 71))
        self.toolButton_push_ten.setObjectName("toolButton_push_ten")
        self.toolButton_eleven = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_eleven.setGeometry(QtCore.QRect(1610, 710, 141, 71))
        self.toolButton_eleven.setObjectName("toolButton_eleven")
        self.toolButton_push_eleven = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_eleven.setGeometry(QtCore.QRect(1750, 710, 141, 71))
        self.toolButton_push_eleven.setObjectName("toolButton_push_eleven")
        self.toolButton_twelve = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_twelve.setGeometry(QtCore.QRect(1610, 780, 141, 71))
        self.toolButton_twelve.setObjectName("toolButton_twelve")
        self.toolButton_push_twelve = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_push_twelve.setGeometry(QtCore.QRect(1750, 780, 141, 71))
        self.toolButton_push_twelve.setObjectName("toolButton_push_twelve")
        self.label_cur_img = QtWidgets.QLabel(self.centralwidget)
        self.label_cur_img.setGeometry(QtCore.QRect(1620, 930, 281, 16))
        self.label_cur_img.setObjectName("label_cur_img")
        self.label_all_img = QtWidgets.QLabel(self.centralwidget)
        self.label_all_img.setGeometry(QtCore.QRect(1620, 880, 281, 16))
        self.label_all_img.setObjectName("label_all_img")
        self.label_savePath = QtWidgets.QLabel(self.centralwidget)
        self.label_savePath.setGeometry(QtCore.QRect(1620, 970, 281, 21))
        self.label_savePath.setObjectName("label_savePath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1931, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolButton_imgdir.clicked.connect(MainWindow.load_img_dir)
        self.toolButton_nextImg.clicked.connect(MainWindow.next_img)
        self.toolButton_preImg.clicked.connect(MainWindow.pre_img)
        self.toolButton_zoom_in.clicked.connect(MainWindow.add_zoom)
        self.toolButton_zoom_out.clicked.connect(MainWindow.subtract_zoom)
        self.toolButton_one.clicked.connect(MainWindow.input_one)
        self.toolButton_push_one.clicked.connect(MainWindow.move_one)
        self.toolButton_two.clicked.connect(MainWindow.input_two)
        self.toolButton_push_two.clicked.connect(MainWindow.move_two)
        self.toolButton_three.clicked.connect(MainWindow.input_three)
        self.toolButton_push_three.clicked.connect(MainWindow.move_three)
        self.toolButton_four.clicked.connect(MainWindow.input_four)
        self.toolButton_push_four.clicked.connect(MainWindow.move_four)
        self.toolButton_push_five.clicked.connect(MainWindow.move_five)
        self.toolButton_five.clicked.connect(MainWindow.input_five)
        self.toolButton_six.clicked.connect(MainWindow.input_six)
        self.toolButton_seven.clicked.connect(MainWindow.input_seven)
        self.toolButton_eight.clicked.connect(MainWindow.input_eight)
        self.toolButton_nine.clicked.connect(MainWindow.input_nine)
        self.toolButton_ten.clicked.connect(MainWindow.input_ten)
        self.toolButton_eleven.clicked.connect(MainWindow.input_eleven)
        self.toolButton_twelve.clicked.connect(MainWindow.input_twelve)
        self.toolButton_push_six.clicked.connect(MainWindow.move_six)
        self.toolButton_push_seven.clicked.connect(MainWindow.move_seven)
        self.toolButton_push_eight.clicked.connect(MainWindow.move_eight)
        self.toolButton_push_nine.clicked.connect(MainWindow.move_nine)
        self.toolButton_push_ten.clicked.connect(MainWindow.move_ten)
        self.toolButton_push_eleven.clicked.connect(MainWindow.move_eleven)
        self.toolButton_push_twelve.clicked.connect(MainWindow.move_twelve)
        self.toolButton_save_path.clicked.connect(MainWindow.input_save_path)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_preImg.setText(_translate("MainWindow", "上一张(A)"))
        self.toolButton_imgdir.setText(_translate("MainWindow", "打开图片文件夹"))
        self.toolButton_nextImg.setText(_translate("MainWindow", "下一张(D)"))
        self.toolButton_zoom_in.setText(_translate("MainWindow", "放大(Space)"))
        self.toolButton_zoom_out.setText(_translate("MainWindow", "缩小"))
        self.toolButton_save_path.setText(_translate("MainWindow", "指定一个保存路径"))
        self.toolButton_push_one.setText(_translate("MainWindow", " <--- 将图片加入(1)"))
        self.toolButton_one.setText(_translate("MainWindow", "设定A类的初始值"))
        self.toolButton_two.setText(_translate("MainWindow", "设定B类的初始值"))
        self.toolButton_push_two.setText(_translate("MainWindow", "<--- 将图片加入(2)"))
        self.toolButton_push_three.setText(_translate("MainWindow", "<--- 将图片加入(3)"))
        self.toolButton_three.setText(_translate("MainWindow", "设定C类的初始值"))
        self.toolButton_push_four.setText(_translate("MainWindow", "<--- 将图片加入(4)"))
        self.toolButton_four.setText(_translate("MainWindow", "设定D类的初始值"))
        self.toolButton_push_five.setText(_translate("MainWindow", "<--- 将图片加入(5)"))
        self.toolButton_five.setText(_translate("MainWindow", "设定E类的初始值"))
        self.toolButton_push_six.setText(_translate("MainWindow", "<--- 将图片加入(6)"))
        self.toolButton_six.setText(_translate("MainWindow", "设定F类的初始值"))
        self.toolButton_push_seven.setText(_translate("MainWindow", "<--- 将图片加入(7)"))
        self.toolButton_seven.setText(_translate("MainWindow", "设定G类的初始值"))
        self.toolButton_eight.setText(_translate("MainWindow", "设定H类的初始值"))
        self.toolButton_push_eight.setText(_translate("MainWindow", "<--- 将图片加入(8)"))
        self.toolButton_nine.setText(_translate("MainWindow", "设定I类的初始值"))
        self.toolButton_push_nine.setText(_translate("MainWindow", "<--- 将图片加入(9)"))
        self.toolButton_ten.setText(_translate("MainWindow", "设定J类的初始值"))
        self.toolButton_push_ten.setText(_translate("MainWindow", "<--- 将图片加入(0)"))
        self.toolButton_eleven.setText(_translate("MainWindow", "设定K类的初始值"))
        self.toolButton_push_eleven.setText(_translate("MainWindow", "<--- 将图片加入(-)"))
        self.toolButton_twelve.setText(_translate("MainWindow", "设定L类的初始值"))
        self.toolButton_push_twelve.setText(_translate("MainWindow", "<--- 将图片加入(=)"))
        self.label_cur_img.setText(_translate("MainWindow", "当前图片"))
        self.label_all_img.setText(_translate("MainWindow", "总图片"))
        self.label_savePath.setText(_translate("MainWindow", "当前保存路径"))
